export const shopItems = [
  {
    id: 1,
    name: 'Gold Container',
    price: 41,
    count: 12,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 2,
    name: 'Gold Container',
    price: 25000,
    count: 15,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 3,
    name: 'Gold Container',
    price: 21,
    count: 222,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 4,
    name: 'Gold Container',
    price: 33,
    count: 152,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 5,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 6,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 7,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 8,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 9,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 10,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 11,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 12,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 13,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 14,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 15,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 16,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },{
    id: 17,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 18,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
  {
    id: 19,
    name: 'Gold Container',
    price: 54,
    count: 15112,
    imgUrl: 'public/img/Shop-item.png',
  },
];